### ISSUE TITLE
Model Weight.

### ISSUE THREAD

**Issue by AMEERAZAM08** [bcmi/SycoNet-Adaptive-Image-Harmonization#1]
when you share model weight?

**Comment by ustcnewly** [comment]
Refer to "Inference" section, the model weights have been released through Baidu Cloud.

**Comment by AMEERAZAM08** [comment]
But in India We can't download from Baidu Cloud which is issue.If possible you can share via some other way .
you can also upload on github also this files are under 50MB

**Comment by ustcnewly** [comment]
I have added the googledrive link.
