### ISSUE TITLE
trilinear does not compile with new torch

### ISSUE THREAD

**Issue by eps696** [bcmi/SycoNet-Adaptive-Image-Harmonization#4]
trilinear cpp extension is not compiled with newer pytorch versions, as dependant on the `THC.h` which was obsoleted from torch.
that's a known issue and torch guys recommend to migrate from `THC` to `ATen`

**Comment by AMEERAZAM08** [comment]
same ? @ustcnewly @cjy-4  if possible can you share the env file and python version

**Comment by AMEERAZAM08** [comment]
and also the nvcc version if CUDA using in this

**Comment by ustcnewly** [comment]
Thanks for your suggestion. We will fix this issue.
