### ISSUE TITLE
训练好的图像和谐模型

### ISSUE THREAD

**Issue by Htcicv** [bcmi/SycoNet-Adaptive-Image-Harmonization#5]
作者您好
  请问咱这边有开源基于Syconet训练好的iS2AM模型吗？我在此项目中没有找到，如果已经开源的话，可以发个链接或者告诉我怎么用吗？
期待您的回复，不胜感激。

**Comment by ustcnewly** [comment]
你好，我们暂时不打算开源和谐化模型。比较简单的做法是先用我们的SycoNet生成大量训练图片，然后在训练iS2AM的时候用增广数据集。
